FROM ollama/ollama:latest

USER root
RUN apt-get update && apt-get install -y python3 python3-pip && ln -s /usr/bin/python3 /usr/bin/python

#RUN apt-get install nano
 
RUN pip install flask 




RUN mkdir data

#RUN pip install hashlib transformers torch 

#COPY ollama/ollama /root/.ollama
